### ISSUE TITLE
I get the empty result alwyas when i call the api 'getResourcesByLocale'

### ISSUE THREAD

**Issue by liantianyun** [crowdin/react-native-sdk#11]
**Describe the bug**
I get the empty result alwyas when i call the api 'getResourcesByLocale'

that's my code:
```
    Crowdin.getResourcesByLocale('en', (data) => {
        var response = JSON.parse(data);
        console.log(response);
        Crowdin.getResourcesByLocale('ja', (data) => {
          var response = JSON.parse(data);
          console.log(response);
      }) 
    })
```
and here is the result's image
![image](https://user-images.githubusercontent.com/45311559/100205333-f2ed1180-2f3f-11eb-91c7-18acee4e7583.png)

 sometime it can work and i got the translation on result's 'string' parm,but mostly it give me empty result. 
is the feature still unstable or something else?

**Comment by serhii-londar** [comment]
@liantianyun Could you specify platform?

**Comment by liantianyun** [comment]
> @liantianyun Could you specify platform?

andorid

**Comment by serhii-londar** [comment]
@liantianyun Thank you. We will check the issue or contact you in case other questions.

**Comment by liantianyun** [comment]
> @liantianyun Thank you. We will check the issue or contact you in case other questions.

thank you. i'm looking forward to your replay because i about to use it

**Comment by liantianyun** [comment]
> @liantianyun Thank you. We will check the issue or contact you in case other questions.

there is a another question.i update and release the translation on
![image](https://user-images.githubusercontent.com/45311559/100211528-35feb300-2f47-11eb-9b8a-6e7d6e5b2c03.png)
but i got the updated data until this time
![image](https://user-images.githubusercontent.com/45311559/100211439-1b2c3e80-2f47-11eb-9854-fcce56d192ad.png)

**Comment by liantianyun** [comment]
> @liantianyun Thank you. We will check the issue or contact you in case other questions.

hi。It seems that this problem has not been repeated today. The difference is that I used the simulator yesterday and the real machine today. You can try to locate what causes the simulator to not work normally, but I can already use it normally
