### ISSUE TITLE
I can't get the translation of ’id‘ and ’he‘

### ISSUE THREAD

**Issue by liantianyun** [crowdin/react-native-sdk#15]
**Describe the bug**
My app support 33 languages, I tested them all again, but I use the 'id', 'he' as languageCode can't take the two language Code translation, other language is normal, before they can lead to program crashes, you in version 0.13 fixes the bug, but now when I call Crowdin. GetResourcesByLocale method, waiting for more than ten seconds callback has not been performed, whether is because, I think you have no for this fetch from increasing the timeout mechanism.Please test and solve this problem as soon as possible. Thank you

**To Reproduce**
1. Call the Crowdin. GetResourcesByLocale with parameter id or he
2. Observe if the callback is executed

**Expected behavior**
To get the translation

**Environment (please complete the following information):**
 - Android
 - React Native 0.62.2
 - Crowdin React Native SDK 0.13

**Smartphone/Simulator/Emulator (please complete the following information):**
 - Oneplus A5000

**Comment by Olena1234** [comment]
Hi! Thank you, passing this to our devs
