### ISSUE TITLE
Not working with RN 0.62.2

### ISSUE THREAD

**Issue by marcoj** [crowdin/react-native-sdk#18]
**Describe the bug**
I'm using react-native: 0.62.2 with this lib v0.1.3 and when I try to build it in XCode I get the `Multiple commands produce (...) /Assets.car` error previously reported in https://github.com/crowdin/react-native-sdk/issues/9
I'm not trying the example app, I'm just implementing the lib.

I've tried to add `install! 'cocoapods', :disable_input_output_paths => true` to my podfile and the error no longer appears but instead is replaced by another
`(...)/node_modules/@crowdin/react-native-sdk/ios/Crowdin.m:51:17: No known class method for selector 'startWithConfig:'`

**To Reproduce**
- yarn add @crowdin/react-native-sdk
- cd ios && pod install
- go to Xcode and build project

**Expected behavior**
Expect the app to run without errors

**Environment (please complete the following information):**
 - OS: macOS
 - React Native version: 0.62.2
 - Crowdin React Native SDK version: 0.1.3

**Smartphone/Simulator/Emulator (please complete the following information):**
 - Device: iOS
 - OS: 12.5

Thanks

**Comment by andrii-bodnar** [comment]
Hi @marcoj!

This React Native SDK currently in beta, so unfortunately some bugs might happen. Try to use our other library - [OTA JavaScript Client](https://github.com/crowdin/react-native-sdk#ota-javascript-client-usage), which also can be integrated into RN application.

**Comment by marcoj** [comment]
That's exactly what I'm trying right now and it appears that it'll be the implemented solution.
Thanks

**Comment by pynkvalerian** [comment]
Hello, I'm also experiencing the same issue with iOS `(...)/node_modules/@crowdin/react-native-sdk/ios/Crowdin.m:51:17: No known class method for selector 'startWithConfig:'`

Environment:
OS: macOS
React Native version: 0.64.3
Crowdin React Native SDK version: 0.1.3

Smartphone/Simulator/Emulator (please complete the following information):
Device: iOS
OS: 14.3

Just thought I should mention it here as well, but I'll try out the OTA JS client as an alternative.
