### ISSUE TITLE
Translation not updated when we release it using over-the-air

### ISSUE THREAD

**Issue by arjundalal** [crowdin/react-native-sdk#31]
Hello Team,
I have created one distribution hash key and on the behalf of that hash key i am updating my translation text. 
i found that it will work for first time but foe another time it will not update the text in React Native.
Team please help me

Thanks in advance

**Comment by andrii-bodnar** [comment]
Hi @arjundalal,

CDN caches all the translations in release for up to 1 hour, and even when new translations are released in Crowdin, CDN may return them with a delay.
