### ISSUE TITLE
[!] No podspec found for `@crowdin` in `../node_modules/@crowdin/react-native-sdk`

### ISSUE THREAD

**Issue by Zestpond** [crowdin/react-native-sdk#6]
Hi all, I have been issue when install and then run `pod install` 

**[!] No podspec found for `@crowdin` in `../node_modules/@crowdin/react-native-sdk`**

**Environment (please complete the following information):**
 - React Native version [e.g. 0.62.2]
 - Crowdin React Native SDK version [e.g. 0.1.0]

**Comment by andrii-bodnar** [comment]
Hi @Zestpond !

Just released a new version - [0.1.1](https://github.com/crowdin/react-native-sdk/releases/tag/0.1.1) with the fix (updated podspec name). 

Could you please check if everything is ok?

**Comment by Zestpond** [comment]
Hi @andrii-bodnar , Thank you. I'll try it
